spring:
  application:
    name: devil-mall
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  main:
    allow-circular-references: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mappercustom/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: mall.fruit.devil.entity,mall.fruit.devil.entitycustom
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mappercustom/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

redis:
  database: devil
  key:
    admin: 'devil:ums:admin'
    resourceList: 'devil:ums:resourceList'
  expire:
    common: 86400 # 24小时



aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tM8knjVDvtE4uAYQ4d6 # 访问身份验证中用到用户标识
    accessKeySecret: 9mQVewqOQd4uaqmmQbNjfnH2DbFp7t # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: devil-fruit # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

minio:
  endpoint: http://43.138.158.204:9000 #MinIO服务所在地址
  bucketName: fruit #存储桶名称
  accessKey: root #访问的key
  secretKey: devil159265 #访问的秘钥
